<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jimuqu</groupId>
        <artifactId>jimuqu-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>jimuqu-common-websocket</artifactId>

    <description>websocket模块</description>

    <dependencies>
        <dependency>
            <groupId>com.jimuqu</groupId>
            <artifactId>jimuqu-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jimuqu</groupId>
            <artifactId>jimuqu-common-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jimuqu</groupId>
            <artifactId>jimuqu-common-cache</artifactId>
        </dependency>
        <!-- 关于solon-websocket https://solon.noear.org/article/643 -->
        <!-- 单独的websocket组件： solon-server-websocket (端口为：主端口 + 10000) / solon-server-websocket-netty (端口为：主端口 + 10000)  -->
        <!-- 支持web-docket的web服务器：（项目中默认使用）solon-server-smarthttp /  solon-server-undertow -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-server-smarthttp</artifactId>
        </dependency>
    </dependencies>

</project>