# 配置数据源对应的 mybatis 信息（要与 DataSource bean 的名字对上）
mybatis.master:
  typeAliases: #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    - "com.jimuqu.**.domain"
  mappers:       #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）；支持目录 ** 或 * 占位符
    - "com.jimuqu.**.mapper.*Mapper"
    - "classpath:mapper/**/*.xml"
  configuration: #扩展配置
    mapperVerifyEnabled: false #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true
    autoMappingBehavior: full #自动映射策略（NONE/PARTIAL/FULL）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl