apiVersion: v1
kind: Service
metadata:
  name: layjava
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989