INSERT INTO `sys_client` (`id`, `client_id`, `client_key`, `client_secret`, `grant_type`, `device_type`, `access_path`, `ip_whitelist`, `active_timeout`, `timeout`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,'e5cd7e4891bf95d1d19206ce24a7b32e','pc','pc123','password,sms,email,social','pc',NULL,NULL,1800,604800,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_client` (`id`, `client_id`, `client_key`, `client_secret`, `grant_type`, `device_type`, `access_path`, `ip_whitelist`, `active_timeout`, `timeout`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,'428a8310cd442757ae699df5d894f051','app','app123','password,sms,social','android','/app/**',NULL,1800,604800,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_config` (`id`, `config_name`, `config_key`, `config_value`, `config_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,'用户管理-账号初始密码','sys.user.initPassword','123456','Y','初始化密码 123456',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_config` (`id`, `config_name`, `config_key`, `config_value`, `config_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,'账号自助-是否开启用户注册功能','sys.account.registerUser','false','Y','是否开启注册用户功能（true开启，false关闭）',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_config` (`id`, `config_name`, `config_key`, `config_value`, `config_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (11,'OSS预览列表资源开关','sys.oss.previewListResource','true','Y','true:开启, false:关闭',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,'sys_normal_disable','系统开关','L','Y','系统开关列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,'sys_common_status','系统状态','L','Y','登录状态列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3,'sys_yes_no','系统是否','L','Y','系统是否列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4,'sys_show_hide','菜单状态','L','Y','菜单状态列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5,'sys_user_gender','用户性别','L','Y','用户性别列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6,'sys_notice_type','通知类型','L','Y','通知类型列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7,'sys_notice_status','通知状态','L','Y','通知状态列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (8,'sys_oper_type','操作类型','L','Y','操作类型列表',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (9,'sys_grant_type','授权类型','L','Y','认证授权类型',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `is_built_in`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (10,'sys_device_type','设备类型','L','Y','客户端设备类型',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,0,1,'正常','0','sys_normal_disable','','primary','Y','正常状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,0,2,'停用','1','sys_normal_disable','','danger','N','停用状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3,0,1,'成功','0','sys_common_status','','primary','N','正常状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4,0,2,'失败','1','sys_common_status','','danger','N','停用状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5,0,1,'是','Y','sys_yes_no','','primary','Y','系统默认是',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6,0,2,'否','N','sys_yes_no','','danger','N','系统默认否',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7,0,1,'显示','0','sys_show_hide','','primary','Y','显示菜单',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (8,0,2,'隐藏','1','sys_show_hide','','danger','N','隐藏菜单',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (9,0,1,'男','0','sys_user_gender','','','Y','性别男',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (10,0,2,'女','1','sys_user_gender','','','N','性别女',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (11,0,3,'未知','2','sys_user_gender','','','N','性别未知',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (12,0,1,'通知','1','sys_notice_type','','warning','Y','通知',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (13,0,2,'公告','2','sys_notice_type','','success','N','公告',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (14,0,1,'正常','0','sys_notice_status','','primary','Y','正常状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (15,0,2,'关闭','1','sys_notice_status','','danger','N','关闭状态',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (16,0,99,'其他','0','sys_oper_type','','info','N','其他操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (17,0,1,'新增','1','sys_oper_type','','info','N','新增操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (18,0,2,'修改','2','sys_oper_type','','info','N','修改操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (19,0,3,'删除','3','sys_oper_type','','danger','N','删除操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (20,0,4,'授权','4','sys_oper_type','','primary','N','授权操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (21,0,5,'导出','5','sys_oper_type','','warning','N','导出操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (22,0,6,'导入','6','sys_oper_type','','warning','N','导入操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (23,0,7,'强退','7','sys_oper_type','','danger','N','强退操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (25,0,9,'清空数据','9','sys_oper_type','','danger','N','清空操作',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (26,0,1,'密码认证','password','sys_grant_type','el-check-tag','default','N','密码认证',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (27,0,2,'短信认证','sms','sys_grant_type','el-check-tag','default','N','短信认证',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (28,0,3,'邮件认证','email','sys_grant_type','el-check-tag','default','N','邮件认证',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (29,0,4,'三方登录认证','social','sys_grant_type','el-check-tag','default','N','三方登录认证',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (30,0,5,'小程序认证','xcx','sys_grant_type','el-check-tag','default','N','小程序认证',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (31,0,1,'PC','pc','sys_device_type','','default','N','PC',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (32,0,2,'安卓','android','sys_device_type','','default','N','安卓',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (33,0,3,'iOS','ios','sys_device_type','','default','N','iOS',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dict_data` (`id`, `parent_id`, `dict_sort`, `dict_label`, `dict_value`, `dict_type_key`, `css_class`, `list_class`, `is_default`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (34,0,4,'小程序','xcx','sys_device_type','','default','N','小程序',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dept` (`id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (100,0,'0','积木区科技',0,NULL,NULL,NULL,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dept` (`id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (101,100,'0,100','总部',1,NULL,NULL,NULL,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dept` (`id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (103,101,'0,100,101','研发部',1,1,NULL,NULL,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dept` (`id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (104,103,'0,100,101,103','平台组',1,NULL,NULL,NULL,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_dept` (`id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (105,101,'0,100,101','市场部',2,NULL,NULL,NULL,'0','0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,'超级管理员','superadmin',1,'1',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,'自定义部门','custom',2,'2',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3,'本部门','department',3,'3',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4,'本部门及以下','department_child',4,'4',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5,'仅本人','self',5,'5',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role` (`id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6,'无权限','no_permission',6,'5',1,1,'0','0',NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role_dept` (`role_id`, `dept_id`) VALUES (2,104);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,103,'admin','系统管理员','sys_user','admin@jimuqu.local','15888888888','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,103,'custom_user','自定义部门用户','sys_user','custom_user@jimuqu.local','13800000002','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3,103,'dept_user','本部门用户','sys_user','dept_user@jimuqu.local','13800000003','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4,103,'dept_child_user','部门及以下用户','sys_user','dept_child_user@jimuqu.local','13800000004','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5,104,'self_user','仅本人用户','sys_user','self_user@jimuqu.local','13800000005','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,104,5,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6,105,'disabled_user','停用用户','sys_user','disabled_user@jimuqu.local','13800000006','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','1','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user` (`id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7,105,'no_permission','无权限用户','sys_user','no_permission@jimuqu.local','13800000007','0',NULL,'$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2','0','0',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (1,1);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (2,2);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (3,3);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (4,4);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (5,5);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (6,5);
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (7,6);
INSERT INTO `sys_post` (`post_id`, `dept_id`, `post_code`, `post_category`, `post_name`, `post_sort`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,103,'ceo',NULL,'董事长',1,'0','0','',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_post` (`post_id`, `dept_id`, `post_code`, `post_category`, `post_name`, `post_sort`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,100,'se',NULL,'项目经理',2,'0','0','',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_post` (`post_id`, `dept_id`, `post_code`, `post_category`, `post_name`, `post_sort`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3,100,'hr',NULL,'人力资源',3,'0','0','',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_post` (`post_id`, `dept_id`, `post_code`, `post_category`, `post_name`, `post_sort`, `status`, `del_flag`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4,100,'user',NULL,'普通员工',4,'0','0','',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_user_post` (`user_id`, `post_id`) VALUES (1,1);
INSERT INTO `sys_notice` (`notice_id`, `notice_title`, `notice_type`, `notice_content`, `status`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,'温馨提醒：2018-07-01 新版本发布啦','2','新版本内容','0','管理员',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_notice` (`notice_id`, `notice_title`, `notice_type`, `notice_content`, `status`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,'维护通知：2018-07-01 系统凌晨维护','1','维护内容','0','管理员',103,1,CURRENT_TIMESTAMP,NULL,NULL);
-- 默认菜单图标按 Bell Plus update_icon.sql 的菜单语义映射，避免直接套用上游菜单 ID。
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1,0,'系统管理',1,'system','',NULL,'N','Y','M','0','0','','eos-icons:system-group',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2,0,'系统监控',2,'monitor','',NULL,'N','Y','M','0','0','','solar:monitor-camera-outline',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (100,1,'用户管理',1,'user','system/user/index',NULL,'N','Y','C','0','0','system:user:list','ant-design:user-outlined',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (101,1,'角色管理',2,'role','system/role/index',NULL,'N','Y','C','0','0','system:role:list','eos-icons:role-binding-outlined',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (102,1,'菜单管理',3,'menu','system/menu/index',NULL,'N','Y','C','0','0','system:menu:list','ic:sharp-menu',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (103,1,'部门管理',4,'dept','system/dept/index',NULL,'N','Y','C','0','0','system:dept:list','mingcute:department-line',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (104,1,'岗位管理',5,'post','system/post/index',NULL,'N','Y','C','0','0','system:post:list','icon-park-outline:appointment',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (105,1,'字典管理',6,'dict','system/dict/index',NULL,'N','Y','C','0','0','system:dict:list','fluent-mdl2:dictionary',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (106,1,'参数设置',7,'config','system/config/index',NULL,'N','Y','C','0','0','system:config:list','ant-design:setting-outlined',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (107,1,'通知公告',8,'notice','system/notice/index',NULL,'N','Y','C','0','0','system:notice:list','fe:notice-push',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (109,1,'客户端管理',11,'client','system/client/index',NULL,'N','Y','C','0','0','system:client:list','solar:monitor-smartphone-outline',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (200,2,'在线用户',1,'online','monitor/online/index',NULL,'N','Y','C','0','0','monitor:online:list','material-symbols:generating-tokens-outline',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (201,2,'操作日志',2,'operlog','monitor/operlog/index',NULL,'N','Y','C','0','0','monitor:operlog:list','arcticons:one-hand-operation',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (202,2,'登录日志',3,'logininfo','monitor/logininfo/index',NULL,'N','Y','C','0','0','monitor:logininfor:list','streamline:interface-login-dial-pad-finger-password-dial-pad-dot-finger',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (300,1,'文件管理',10,'oss','system/oss/index',NULL,'N','Y','C','0','0','system:oss:list','solar:folder-with-files-outline',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (301,1,'文件配置管理',10,'oss-config/index','system/oss/config',NULL,'N','N','C','1','0','system:ossConfig:list','ant-design:setting-outlined','/system/oss',NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES
(1000,100,'用户查询',1,'','',NULL,'N','Y','F','0','0','system:user:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1001,100,'用户新增',2,'','',NULL,'N','Y','F','0','0','system:user:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1002,100,'用户修改',3,'','',NULL,'N','Y','F','0','0','system:user:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1003,100,'用户删除',4,'','',NULL,'N','Y','F','0','0','system:user:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1004,100,'用户导出',5,'','',NULL,'N','Y','F','0','0','system:user:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1005,100,'用户导入',6,'','',NULL,'N','Y','F','0','0','system:user:import','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1006,100,'重置密码',7,'','',NULL,'N','Y','F','0','0','system:user:resetPwd','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1010,101,'角色查询',1,'','',NULL,'N','Y','F','0','0','system:role:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1011,101,'角色新增',2,'','',NULL,'N','Y','F','0','0','system:role:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1012,101,'角色修改',3,'','',NULL,'N','Y','F','0','0','system:role:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1013,101,'角色删除',4,'','',NULL,'N','Y','F','0','0','system:role:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1014,101,'角色导出',5,'','',NULL,'N','Y','F','0','0','system:role:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1020,102,'菜单查询',1,'','',NULL,'N','Y','F','0','0','system:menu:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1021,102,'菜单新增',2,'','',NULL,'N','Y','F','0','0','system:menu:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1022,102,'菜单修改',3,'','',NULL,'N','Y','F','0','0','system:menu:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1023,102,'菜单删除',4,'','',NULL,'N','Y','F','0','0','system:menu:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1030,103,'部门查询',1,'','',NULL,'N','Y','F','0','0','system:dept:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1031,103,'部门新增',2,'','',NULL,'N','Y','F','0','0','system:dept:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1032,103,'部门修改',3,'','',NULL,'N','Y','F','0','0','system:dept:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1033,103,'部门删除',4,'','',NULL,'N','Y','F','0','0','system:dept:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1040,104,'岗位查询',1,'','',NULL,'N','Y','F','0','0','system:post:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1041,104,'岗位新增',2,'','',NULL,'N','Y','F','0','0','system:post:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1042,104,'岗位修改',3,'','',NULL,'N','Y','F','0','0','system:post:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1043,104,'岗位删除',4,'','',NULL,'N','Y','F','0','0','system:post:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1044,104,'岗位导出',5,'','',NULL,'N','Y','F','0','0','system:post:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1050,105,'字典查询',1,'','',NULL,'N','Y','F','0','0','system:dict:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1051,105,'字典新增',2,'','',NULL,'N','Y','F','0','0','system:dict:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1052,105,'字典修改',3,'','',NULL,'N','Y','F','0','0','system:dict:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1053,105,'字典删除',4,'','',NULL,'N','Y','F','0','0','system:dict:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1054,105,'字典导出',5,'','',NULL,'N','Y','F','0','0','system:dict:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1060,106,'参数查询',1,'','',NULL,'N','Y','F','0','0','system:config:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1061,106,'参数新增',2,'','',NULL,'N','Y','F','0','0','system:config:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1062,106,'参数修改',3,'','',NULL,'N','Y','F','0','0','system:config:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1063,106,'参数删除',4,'','',NULL,'N','Y','F','0','0','system:config:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1064,106,'参数导出',5,'','',NULL,'N','Y','F','0','0','system:config:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `order_num`, `path`, `component`, `query_param`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `active_menu`, `ext`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES
(1100,107,'公告查询',1,'','',NULL,'N','Y','F','0','0','system:notice:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1101,107,'公告新增',2,'','',NULL,'N','Y','F','0','0','system:notice:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1102,107,'公告修改',3,'','',NULL,'N','Y','F','0','0','system:notice:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1103,107,'公告删除',4,'','',NULL,'N','Y','F','0','0','system:notice:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1110,109,'客户端查询',1,'','',NULL,'N','Y','F','0','0','system:client:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1111,109,'客户端新增',2,'','',NULL,'N','Y','F','0','0','system:client:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1112,109,'客户端修改',3,'','',NULL,'N','Y','F','0','0','system:client:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1113,109,'客户端删除',4,'','',NULL,'N','Y','F','0','0','system:client:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1114,109,'客户端导出',5,'','',NULL,'N','Y','F','0','0','system:client:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1120,200,'强制退出',1,'','',NULL,'N','Y','F','0','0','monitor:online:forceLogout','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1121,201,'日志导出',1,'','',NULL,'N','Y','F','0','0','monitor:operlog:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1122,201,'日志删除',2,'','',NULL,'N','Y','F','0','0','monitor:operlog:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1130,202,'日志导出',1,'','',NULL,'N','Y','F','0','0','monitor:logininfor:export','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1131,202,'日志删除',2,'','',NULL,'N','Y','F','0','0','monitor:logininfor:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1132,202,'账户解锁',3,'','',NULL,'N','Y','F','0','0','monitor:logininfor:unlock','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1140,300,'文件查询',1,'','',NULL,'N','Y','F','0','0','system:oss:query','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1141,300,'文件上传',2,'','',NULL,'N','Y','F','0','0','system:oss:upload','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1142,300,'文件下载',3,'','',NULL,'N','Y','F','0','0','system:oss:download','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1143,300,'文件删除',4,'','',NULL,'N','Y','F','0','0','system:oss:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1144,300,'配置列表',5,'','',NULL,'N','Y','F','0','0','system:ossConfig:list','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1150,300,'配置新增',1,'','',NULL,'N','Y','F','0','0','system:ossConfig:add','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1151,300,'配置修改',2,'','',NULL,'N','Y','F','0','0','system:ossConfig:edit','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL),
(1152,300,'配置删除',3,'','',NULL,'N','Y','F','0','0','system:ossConfig:remove','',NULL,NULL,NULL,103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_oss_config` (`oss_config_id`, `config_key`, `access_key`, `secret_key`, `bucket_name`, `prefix`, `endpoint`, `domain_url`, `is_https`, `region`, `status`, `ext1`, `remark`, `access_policy`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1761900000000000001,'default',NULL,NULL,NULL,'',NULL,NULL,'N','', 'Y','',NULL,'0',103,1,CURRENT_TIMESTAMP,NULL,NULL);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (2,1);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (2,100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (3,1);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (3,100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (4,1);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (4,100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (5,1);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (5,100);
