# common配置，非必要情况下不用修改
# server配置
server.port: 5320

solon:
  # 应用环境配置
  env: @profiles.active@
  # 应用配置
  app:
    #应用名称
    name: jimuqu-admin
    #应用标题
    title: "积木区-Admin"
    #应用组
    group: "jimuqu"
    # 版本
    version: @revision@

# 线上环境支持外部配置
---
solon.env.on: prod
solon.config.add: "./app.yml"
---

# 批量加载内部配置
solon.config.load:
  - "config/*.yml"

# 记录器级别的配置示例
solon.logging.logger:
  # 关闭autotable的输出日志，默认是INFO级别
  "org.dromara.autotable.core.utils.DBHelper":
    level: WARN
  "org.dromara.autotable.core":
    level: WARN
  # redis连接时的日志
  "org.redisson.connection":
    level: WARN
  # 修改日志级别
  "com.zaxxer.hikari":
    level: WARN

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login

# 本地缓存
jimuqu.cache:
  driverType: "local" #缓存类型
  keyHeader: "jimuqu"

# 代码生成
gen:
  # 作者
  author: chengliang4810
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.jimuqu.system
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
  # 使用的模版 默认是vben，原生的是vue
  platform: vue

# 表自动配置
auto-table:
  enable: true
  show-banner: false
  # 自定义的索引前缀
  index-prefix: idx_
  # 自动删除数据库中多余的列
  auto-drop-column: false
  # 自动删除数据库中多余的索引
  auto-drop-index: false
  # update(默认)：系统启动时，会自动判断哪些表是新建的，哪些字段要新增修改，哪些索引/约束要新增删除等。
  model: update
  # 记录表信息维护过程中执行的SQL
  recordSql:
    enable: true
    # 记录方式，默认是数据库，可选文件(file)方式
    recordType: custom
    # 当前SQL的版本，建议指定，会体现在数据库的字段或者文件名上
    version: ${revision}
    # 记录文件的路径
    folderPath: ./db/sql
