# common配置，非必要情况下不用修改
# 多数情况下是将配置的默认值写出来方便修改，所以看起来多
# server配置
server.port: 5320

solon:
  # 应用环境配置
  env: @profiles.active@
  # 应用配置
  app:
    #应用名称
    name: jimuqu-admin
    #应用标题
    title: "积木区-Admin"
    #应用组
    group: "jimuqu"
    # 版本
    version: @revision@

# 线上环境支持外部配置
---
solon.env.on: prod
solon.config.add: "./app.yml"
---

# 批量加载内部配置
solon.config.load:
  - "config/*.yml"

# 记录器级别的配置示例
solon.logging.logger:
  # 关闭autotable的输出日志，默认是INFO级别
  "org.dromara.autotable.core.utils.DBHelper":
    level: WARN
  "org.dromara.autotable.core":
    level: WARN
  # redis连接时的日志
  "org.redisson.connection":
    level: WARN
  # 修改日志级别
  "com.zaxxer.hikari":
    level: WARN

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login

# 本地缓存
jimuqu.cache:
  driverType: "local" #缓存类型
  keyHeader: "jimuqu"

# 表自动配置
auto-table:
  enable: true
  show-banner: false
  # 自定义的索引前缀
  index-prefix: idx_
  # 自动删除数据库中多余的列
  auto-drop-column: false
  # 自动删除数据库中多余的索引
  auto-drop-index: false
  # 数据库不存在自动创建
  auto-build-database: true
  # update(默认)：系统启动时，会自动判断哪些表是新建的，哪些字段要新增修改，哪些索引/约束要新增删除等。
  mode: update
  # 初始化数据配置
  init-data:
    # 是否开启初始化数据功能
    enable: true
    # 初始化数据文件名，默认是_init_.sql
    default-init-file-name: jimuqu.sql
    # 初始化数据文件路径
    base-path: classpath:sql/{dialect}
  # 记录表信息维护过程中执行的SQL
  recordSql:
    enable: true
    # 记录方式，默认是数据库，可选文件(file)方式 custom方式(已实现flyway规范的SQL记录，类：RecordSqlFlywayHandler)
    recordType: file
    # 当前SQL的版本，建议指定，会体现在数据库的字段或者文件名上
    version: ${revision}
    # 记录文件的路径
    folderPath: ./db/sql

# OSS配置
dromara:
  x-file-storage: #文件存储配置
    default-platform: local-plus #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    enable-multipart-file-wrapper: false #是否启用多文件包装器
    enable-http-servlet-request-file-wrapper: false
    local-plus: # local-plus代表x-file-storage中的平台类型，不可以随意更改
      - platform: default # 存储平台标识，用户自定义的标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://127.0.0.1:8080/file/ # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /file/ # 访问路径
        storage-path: D:/temp/ # 存储路径
#    minio: # minio 存储类型的使用方式
#      - platform: minio-user # 存储平台标识
#        enable-storage: true  # 启用存储
#        access-key: j9rMyECcmNH0lNBqPfOo
#        secret-key: 0NYFJSl4D8msuxHirenthXA4lvju4c3QNdmQ29Ob
#        end-point: http://127.0.0.1:9000
#        bucket-name: user
#        #        domain: ?? # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
#        base-path: user/ # 基础路径
#      - platform: minio-dept # 存储平台标识
#        enable-storage: true  # 启用存储
#        access-key: j9rMyECcmNH0lNBqPfOo
#        secret-key: 0NYFJSl4D8msuxHirenthXA4lvju4c3QNdmQ29Ob
#        end-point: http://127.0.0.1:9000
#        bucket-name: dept
#        #        domain: ?? # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
#        base-path: dept/ # 基础路径

