# common配置，非必要情况下不用修改
# 应用环境配置
solon.env: @profiles.active@
#应用名称
solon.app.name: layjava-admin
#应用标题
solon.app.title: "LayJavaAdmin"
#应用组
solon.app.group: "layjava"

# 添加外部扩展配置
---
solon.env.on: prod
solon.config.add: "./app.yml"

--- # mybatis plus
mybatis.db:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliases:
    - "com.layjava.**.domain"
  mappers:
    # 对应Mapper接口位置
    - "com.layjava.**.mapper"
    # 对应的 XML 文件位置
    - "mapper/**/*Mapper.xml"

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login
    - /swagger/v2