# common配置，非必要情况下不用修改
# server配置
server.port: 8989

solon:
  # 应用环境配置
  env: @profiles.active@
  # 应用配置
  app:
    #应用名称
    name: layjava-admin
    #应用标题
    title: "LayJavaAdmin"
    #应用组
    group: "layjava"
    # 版本
    version: @revision@

# 线上环境支持外部配置
---
solon.env.on: prod
solon.config.add: "./app.yml,./app-prod.yml"
---

# 批量加载内部配置
solon.config.load:
  - "config/*.yml"

# 记录器级别的配置示例
solon.logging.logger:
  "com.zaxxer.hikari":
    level: WARN

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    - version
    # 登录
    - /auth/login

# 本地缓存
layjava.cache:
  driverType: "local" #缓存类型
  keyHeader: "layjava"

# 代码生成
gen:
  # 作者
  author: chengliang4810
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.layjava.system
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
  # 使用的模版 默认是vben，原生的是vue
  platform: vben
