# common配置，非必要情况下不用修改
# server配置
server.port: 8989

# 应用环境配置
solon.env: @profiles.active@
#应用名称
solon.app.name: layjava-admin
#应用标题
solon.app.title: "LayJavaAdmin"
#应用组
solon.app.group: "layjava"

# 添加外部扩展配置
---
solon.env.on: prod
solon.config.add: "./app.yml"

---
solon.config.load:
  - "config/*.yml"

# 记录器级别的配置示例
solon.logging.logger:
  "com.zaxxer.hikari":
    level: WARN

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login

--- ## Web序列化配置
solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
  dateAsTimeZone: 'GMT+8' #配置时区
  dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
  longAsString: false #将long型转为字符串输出 （默认为false）
  boolAsInt: false   #将bool型转为字符串输出 （默认为false）
  nullStringAsEmpty: false
  nullBoolAsFalse: false
  nullNumberAsZero: false
  nullArrayAsEmpty: false
  nullAsWriteable: false #输出所有null值
  enumAsName: true #枚举使用名字（v2.2.1 后支持）