# common配置，非必要情况下不用修改
# 应用环境配置
solon.env: @profiles.active@
#应用名称
solon.app.name: layjava-admin
#应用标题
solon.app.title: "LayJavaAdmin"
#应用组
solon.app.group: "layjava"

# 添加外部扩展配置
---
solon.env.on: prod
solon.config.add: "./app.yml"

--- # mybatis plus
mybatis.default:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliases:
    - "com.layjava.**.domain"
  # 对应Mapper接口位置
  mappers:
    - "com.layjava.**.mapper.*Mapper"
    # 对应的 XML 文件位置
    - "classpath:mapper/**/*Mapper.xml"

--- # bean searcher配置统一分页条件
bean-searcher:
  enable: false
  params:
    pagination:
      page: pageNum
      size: pageSize
      start: 1

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login
    - /swagger/v2
    - /test/user/**

--- # 验证码
aj.captcha:
  enable: true
  # aes加密坐标开启或者禁用(true|false)
  aes-status: true
  # 缓存local/redis...
  cache-type: local
  history-data-clear-enable: false
  # 滑动干扰项(0/1/2)
  interference-options: 2
  # 滑动验证，底图路径，不配置将使用默认图片 。社区底图资源 https://gitee.com/anji-plus/AJ-Captcha-Images
  # 支持全路径
  # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
  #    jigsaw: classpath:images/jigsaw
  # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
  #    pic-click: classpath:images/pic-click
  # check接口一分钟内请求数限制
  req-check-minute-limit: 60
  # 接口请求次数一分钟限制是否开启 true|false
  req-frequency-limit-enable: true
  # 验证失败5次，get接口锁定
  req-get-lock-limit: 5
  # 验证失败后，锁定时间间隔,s
  req-get-lock-seconds: 360
  # get接口一分钟内请求数限制
  req-get-minute-limit: 30
  # check接口一分钟内请求数限制
  req-verify-minute-limit: 60
  # 校验滑动拼图允许误差偏移量(默认5像素)
  slip-offset: 5
  # 验证码类型default两种都实例化。
  type: default
  # 汉字统一使用Unicode,保证程序通过@value读取到是中文，可通过这个在线转换;yml格式不需要转换
  # https://tool.chinaz.com/tools/unicode.aspx 中文转Unicode
  water-mark: layjava.com

## Web序列化配置
solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
  dateAsTimeZone: 'GMT+8' #配置时区
  dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
  longAsString: true #将long型转为字符串输出 （默认为false）
  boolAsInt: false   #将bool型转为字符串输出 （默认为false）
  nullStringAsEmpty: false
  nullBoolAsFalse: false
  nullNumberAsZero: false
  nullArrayAsEmpty: false
  nullAsWriteable: false #输出所有null值
  enumAsName: true #枚举使用名字（v2.2.1 后支持）