# common配置，非必要情况下不用修改
# server配置
server.port: 8989

# 应用环境配置
solon.env: @profiles.active@
#应用名称
solon.app.name: layjava-admin
#应用标题
solon.app.title: "LayJavaAdmin"
#应用组
solon.app.group: "layjava"

# 添加外部扩展配置
---
solon.env.on: prod
solon.config.add: "./app.yml"

---
solon.config.load:
  - "config/*.yml"

# 记录器级别的配置示例
solon.logging.logger:
  "com.zaxxer.hikari":
    level: WARN

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login

# 本地缓存
layjava.cache:
  driverType: "caffeine" #缓存类型
  keyHeader: "layjava"
