kind: pipeline
type: docker
name: default

steps:
  # maven 打包jar
  - name: package-jar
    image: maven:3.9.9-amazoncorretto-17
    timeout: 3m
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设 置
      - name: maven_cache
        path: /root/.m2 # 将maven下载依赖的目录挂载出来，防止重复下载\
      - name: app
        path: /app
    commands:
      # 打包jar
      - mvn clean package -DskipTests=true
      # 复制jar到指定目录, 本机部署时有用
      # - cp layjava-admin/target/layjava-admin.jar /app/layjava-admin.jar
      # 复制jar到当前目录， scp发送
      - cp layjava-admin/target/layjava-admin.jar ./layjava-admin.jar
    # 指定runner名称
    node: [ "wangsr-docker-runner" ]
    # 触发条件
    trigger:
      branch:
        - master
      event:
        - push

  - name: deployment-jar
    image: appleboy/drone-scp
    # 指定runner名称
    node: [ "wangsr-docker-runner" ]
    settings:
      host:
        from_secret: remote_host
      username:
        from_secret: remote_user
      password:
        from_secret: remote_ps
      port: 22
      target: /app/layjava-admin/api
      source: layjava-admin.jar
    depends_on:
      - package-jar
    when:
      branch: master

# 钉钉通知
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    # 指定runner名称
    node: [ "wangsr-docker-runner" ]
    settings:
      type: markdown
      tpl: /tpl/markdown.tpl
      token:
        from_secret: dingding_token
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设 置
      - name: dingtalk
        path: /tpl
    depends_on:
      - package-jar
      - deployment-jar

  # 构建docker镜像, 本地部署时有用
#  - name: restart-docker-image
#    image: plugins/docker
#    pull: if-not-exists
#    commands:
#      - docker restart layjava-admin-api
#    # 指定runner名称
#    node: ["layjava-docker-runner"]
#    # 触发条件
#    trigger:
#      event:
#        - push
#      branch:
#        - master

# 映射主机目录
volumes:
  # maven仓库目录，避免重复下载依赖
  - name: maven_cache
    host:
      path: /storge/drone/cache
  # docker的
  - name: socker
    host:
      path: /var/run/docker.sock
  - name: app
    host:
      path: /app/layjava-admin/api
  - name: dingtalk
    host:
      path: /app/dingtalk