kind: pipeline
type: docker
name: default

steps:
  # maven 打包jar
  - name: package-jar
    image: maven:3.9.9-amazoncorretto-17
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设 置
      - name: maven_cache
        path: /root/.m2 # 将maven下载依赖的目录挂载出来，防止重复下载\
      - name: app
        path: layjava-admin/target/
    commands:
      - mvn clean package -DskipTests=true
    # 指定runner名称
    node: [ "layjava-docker-runner" ]
    # 触发条件
    trigger:
      event:
        - push
    # 分支条件
    when:
      branch:
        - master

  # 构建docker镜像
  - name: restart-docker-image
    image: plugins/docker
    pull: if-not-exists
    commands:
      - docker restart layjava-admin-api
    # 指定runner名称
    node: ["layjava-docker-runner"]
    # 触发条件
    trigger:
      event:
        - push
    # 分支条件
    when:
      branch:
        - master

# 映射主机目录
volumes:
  - name: maven_cache
    host:
      path: /storge/drone/cache
  - name: socker
    host:
      path: /var/run/docker.sock
  - name: app
    host:
      path: /app/layjava-admin/api