-- 字典类型初始值

INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1, 'sys_user_sex', '用户性别', 'L', '用户性别列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2, 'sys_show_hide', '菜单状态', 'L', '菜单状态列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3, 'sys_normal_disable', '系统开关', 'L', '系统开关列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6, 'sys_yes_no', '系统是否', 'L', '系统是否列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7, 'sys_notice_type', '通知类型', 'L', '通知类型列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (8, 'sys_notice_status', '通知状态', 'L', '通知状态列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (9, 'sys_oper_type', '操作类型', 'L', '操作类型列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (10, 'sys_common_status', '系统状态', 'L', '登录状态列表', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (11, 'sys_grant_type', '授权类型', 'L', '认证授权类型', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_key`, `dict_name`, `dict_type`, `remark`, `create_dept`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (12, 'sys_device_type', '设备类型', 'L', '客户端设备类型', 103, 1, '2024-07-31 18:46:52', NULL, NULL);
