<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jimuqu</groupId>
        <artifactId>jimuqu-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>jimuqu-common-web</artifactId>
    <description>web模块</description>

    <dependencies>
        <dependency>
            <groupId>com.jimuqu</groupId>
            <artifactId>jimuqu-common-core</artifactId>
        </dependency>

        <!-- Http 启动器（包大小:0.8Mb，aio, http, ws） -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-server-smarthttp</artifactId>
        </dependency>

        <!-- 更强的Http 启动器（包大小:4.8Mb，nio, http, ws, http2） -->
<!--        <dependency>-->
<!--            <groupId>org.noear</groupId>-->
<!--            <artifactId>solon-server-undertow</artifactId>-->
<!--        </dependency>-->

        <!-- Json序列化支持组件 -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-serialization-snack4</artifactId>
        </dependency>

        <!-- 跨域处理组件 -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-web-cors</artifactId>
        </dependency>

        <!-- 日志 -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-logging-logback</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool.v7</groupId>
            <artifactId>hutool-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>


</project>
