[supervisord]
nodaemon=true
logfile=/var/log/jimuqu/supervisord.log

[program:redis]
command=/usr/bin/redis-server --requirepass P@ssw0rd
autorestart=true

[program:backend]
command=/usr/bin/java -Dserver.port=5320 -Dsolon.env=prod -jar /opt/jimuqu/app.jar
directory=/opt/jimuqu
autorestart=true
stdout_logfile=/var/log/jimuqu/backend.log
stderr_logfile=/var/log/jimuqu/backend-error.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/jimuqu/nginx.log
stderr_logfile=/var/log/jimuqu/nginx-error.log
