easy-query.default:
  enable: true
  # 目前仅支持mysql
  database: mysql
  # 采用下划线userAge将对应数据库user_age
  name-conversion: underlined
  # 允许物理删除
  delete-throw: false
  # 参数打印风格: MYBATIS/DEFAULT
  sqlParameterPrint: MYBATIS
  # #sqlNativeSegment输入和格式化无需处理单引号会自动处理为双单引号
  keep-native-style: true