<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jimuqu</groupId>
        <artifactId>jimuqu-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>jimuqu-common-satoken</artifactId>
    <description>satoken模块</description>
    
    <dependencies>
        <dependency>
            <groupId>com.jimuqu</groupId>
            <artifactId>jimuqu-common-cache</artifactId>
        </dependency>
        <!-- sa-token -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-solon-plugin</artifactId>
        </dependency>
        <!-- Sa-Token 整合 JWT（Simple 模式） -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-jwt</artifactId>
        </dependency>
        <!-- sa-token redisson依赖, 使用redis时加入。 -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-redisson</artifactId>
        </dependency>
        <!-- sa-token snack4 序列化框架 -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-snack4</artifactId>
        </dependency>

        <!-- sa-token snack4 序列化框架： sa-token 需要春节左右发新，所以Solon临时发了个包 -->
<!--        <dependency>-->
<!--            <groupId>org.noear</groupId>-->
<!--            <artifactId>sa-token-snack4</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>


</project>
